### ISSUE TITLE
meson build error - "c++20"

### ISSUE THREAD

**Issue by fffed** [ErikReider/SwayAudioIdleInhibit#1]
When I run `meson build` on Ubuntu 21.04 I got an error:
`meson.build:1:0: ERROR: Value "c++20" (of type "string") for combo option "C++ language standard to use" is not one of the choices. Possible choices are (as string): "none", "c++98", "c++03", "c++11", "c++14", "c++17", "c++1z", "c++2a", "gnu++03", "gnu++11", "gnu++14", "gnu++17", "gnu++1z", "gnu++2a".`

messon -- version: 0.56.2

To fix this I replaced this [meson.build:5](https://github.com/ErikReider/SwayAudioIdleInhibit/blob/main/meson.build#L5) with
`default_options: ['warning_level=3', 'cpp_std=c++2a'],`

**Comment by ErikReider** [comment]
Oh. Mb. I'll fix that immediately

**Comment by ErikReider** [comment]
I removed the default_options all together so it should be working now
