### ISSUE TITLE
No longer works with latest commit using the latest wlroots

### ISSUE THREAD

**Issue by deprecated-dot** [ErikReider/SwayAudioIdleInhibit#10]
Using very latest wlroots (commit, at time of writing: 8714657d) with the latest commit of SwayAudioIdleInhibit.

Calling `sway-audio-idle-inhibit` with no options will show `IDLE INHIBITED` as expected, but it doesn't actually prevent idle anymore. 

On a whim, I wrote a patch to revert the `wl_display_sync(display);` sections back to `wl_display_roundtrip(display);`, and it works again.

I'm not a wlroots expert, but I figured I'd report it anyway in case it's of help to you.

For reference, I'm running Gentoo with bleeding-edge sway and wlroots, and have "packaged" SwayAudioIdleInhibit in my local portage repository.

**Comment by Druneau** [comment]
I can confirm I am getting same thing since the change in PR#9.  I was focused on testing for the crash and did not think to test if the program was still working as expected...
