### ISSUE TITLE
--dry-print-both-waybar doesn't update on status change

### ISSUE THREAD

**Issue by nrdxp** [ErikReider/SwayAudioIdleInhibit#19]
The output from invoking the `--dry-print-both-waybar` does not update when there is a change to the inhibitor status. This makes using it in a waybar custom module fairly useless since the bar will not update when audio starts and stops.

Possible solution would simply be to update the output buffer with the new information when the status changes, or perhaps use a singal like SIGPOLL which waybar can be configured to send to the process to update the output.

**Comment by ErikReider** [comment]
I'll be removing this functionality soon now that my privacy module has been merged into Waybar, so use that instead
