### ISSUE TITLE
--dry-print-sink always reports RUNNING

### ISSUE THREAD

**Issue by Zeioth** [ErikReider/SwayAudioIdleInhibit#2]
This happens even if nothing is playing, and all applications are closed. There is a way to debug what could be causing this?

I'm in manjaro-sway using pipewire-pulse.

**Comment by ErikReider** [comment]
Run `pactl list sink-inputs`. Make sure that all Sink Inputs have `corked` set to `yes`

**Comment by Zeioth** [comment]
Thank you. It seems spotifyd is never corked, even if it's stopped. I'll report that to them.
![screenshot_2021-12-08_19-26-33_611604890](https://user-images.githubusercontent.com/3357792/145263471-9d6181b6-6a98-4c89-84f9-6d98f7c6001b.png)

**Comment by ErikReider** [comment]
👍
