### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by OriginCode** [ErikReider/SwayAudioIdleInhibit#22]
Hi, I'm a distro packager, just want to know if there will be a version release recently, the last release is already 2 years ago.

**Comment by rafaelrc7** [comment]
I maintain this package in nixpkgs. I would also appreciate a new release

**Comment by sigboe** [comment]
@ErikReider Excuse me for pinging, please consider making a new release now. I am using both Arch and Nixos, and there are a few bugs that I experience regularly that seams to already be addressed from reading the commit messages.

Thank you very much!

**Comment by ErikReider** [comment]
Done :)
